"""Model code for a depth-stepped Neural SPDE calorimeter shower model. See
nspde2d-voxel.ipynb for data loading, training/eval orchestration, and plotting.

Formulation
-----------
The voxel grid (Z, PHI, R) = (45, 16, 9) is read as a (2+1)-dimensional space-time
domain: the transverse (PHI, R) plane is the 2D *space*, and the Z-depth axis (the
45 calorimeter layers) is *time*. A shower is generated by solving the SPDE

    dy = f_theta(t, y) dt + g_theta(t, y) . noise

forward from layer t=0 to t=44, where:
  - y(t) is the *energy fraction* (shower_MeV / E_inc_MeV) deposited in each voxel
    of layer t -- kept in linear (not log-normalized) space, so the additive drift
    and multiplicative diffusion below stay physically meaningful (log-energy does
    not obey the same conservation / shot-noise relationships).
  - f_theta, g_theta ("drift" and "diffusion") are *learned spatial operators* --
    stacks of FNO-style spectral-convolution layers (SpectralConv2d /
    FourierLayer2d) over the (PHI, R) plane, conditioned on t and log10(E_inc).
    This is the "neural" + "spatial operator" part of a Neural SPDE (Salvi,
    Lemercier & Gerasimovics, arXiv:2110.10249), applied here as a depth-stepped
    solver rather than that paper's single-shot whole-space-time fixed-point solve.
  - `noise` is a pluggable driving stochastic process (see NoiseProcess and its
    subclasses below): BrownianNoise / ColoredBrownianNoise (Wiener-driven, exact
    Euler-Maruyama training likelihood) or CompoundPoissonNoise (jump-driven,
    closer to true shot noise from discrete particle depositions; trained via a
    moment-matched Gaussian surrogate but *sampled* as real sparse jumps).

This directly extends sde_demo.ipynb's `CaloSDE` prototype (fixed mean-reversion
drift towards a precomputed mean shower profile + fixed sqrt(E) shot-noise
diffusion, integrated with torchsde) by replacing both fixed functional forms with
learned spectral networks, and by making the driving noise process itself
swappable instead of hard-wired.

Training is teacher-forced: every transition (layer t -> t+1) is scored against
real Geant4 data in one vectorized batch (see NeuralSPDE.teacher_forced_loss), not
by an actual sequential rollout -- only free-running generation
(NeuralSPDE.simulate) does real step-by-step integration.
"""

import math
import datetime
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
import wandb
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR, LinearLR, SequentialLR


def sinusoidal_embedding(t: torch.Tensor, dim: int) -> torch.Tensor:
    """Sinusoidal embedding (Vaswani et al.); works for the discrete depth index t."""
    half  = dim // 2
    freqs = torch.exp(
        -math.log(10000) * torch.arange(half, device=t.device) / (half - 1)
    )
    args = t[:, None].float() * freqs[None]
    return torch.cat([args.sin(), args.cos()], dim=-1)  # (B, dim)


class DepthTimeEmbedding(nn.Module):
    """Embeds the discrete depth-layer index t in [0, 44] (the SPDE's time axis)."""

    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim
        self.net = nn.Sequential(
            nn.Linear(dim, dim * 4), nn.SiLU(), nn.Linear(dim * 4, dim * 4),
        )

    def forward(self, t: torch.Tensor):
        return self.net(sinusoidal_embedding(t, self.dim))  # (B, dim*4)


class EnergyEmbedding(nn.Module):
    """Embeds log10(E_inc / MeV)."""

    def __init__(self, dim: int):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(1, dim), nn.SiLU(), nn.Linear(dim, dim))

    def forward(self, cond: torch.Tensor):
        return self.net(cond.unsqueeze(-1))  # (B, dim)


class CumulativeEnergyEmbedding(nn.Module):
    """Embeds the fraction of E_inc deposited so far (summed over all layers up to
    and including the current one). Gives drift_net/diffusion_net the "how much have
    I already used up" state they were missing -- without it, neither network can
    represent "stop depositing energy" as a function of anything except the depth
    index t, which is why containment past shower-max wasn't learned (see README.md,
    "Containment isn't learned"). Bounded in [0, ~1] (a fraction, not a decade-spanning
    quantity like E_inc), so fed raw -- no log transform needed the way EnergyEmbedding
    needs one for E_inc."""

    def __init__(self, dim: int):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(1, dim), nn.SiLU(), nn.Linear(dim, dim))

    def forward(self, cum_frac: torch.Tensor):
        return self.net(cum_frac.unsqueeze(-1))  # (B, dim)


# ── Spectral (FNO-style) spatial operator over the (phi, r) plane ──────────────

class SpectralConv2d(nn.Module):
    """FNO-style spectral convolution: a truncated-mode complex-linear map applied
    in Fourier space over the last two (spatial) dims.

    Two separate weight blocks (w_pos / w_neg) are needed because rfft2 only halves
    the *last* dim (R here) via real-signal conjugate symmetry -- the second-to-last
    dim (PHI here, genuinely periodic) keeps its full spectrum, wrapped so low
    negative frequencies live at the high-index end of the array. Truncating with a
    single low-index block would asymmetrically keep only low positive PHI
    frequencies and silently drop their low-negative counterparts.
    """

    def __init__(self, in_channels: int, out_channels: int, modes_h: int, modes_w: int):
        super().__init__()
        self.modes_h, self.modes_w = modes_h, modes_w
        scale = 1.0 / (in_channels * out_channels)
        self.w_pos = nn.Parameter(scale * torch.randn(in_channels, out_channels, modes_h, modes_w, dtype=torch.cfloat))
        self.w_neg = nn.Parameter(scale * torch.randn(in_channels, out_channels, modes_h, modes_w, dtype=torch.cfloat))

    def forward(self, x: torch.Tensor):
        B, C, H, W = x.shape
        orig_dtype = x.dtype
        # cuFFT has no bf16/fp16 kernels, so rfft2/irfft2 must run outside autocast
        # (in fp32) even when the rest of the model is autocast to bf16 -- see
        # train()'s amp_dtype for why bf16 autocast is used at all.
        with torch.autocast(x.device.type, enabled=False):
            x_ft = torch.fft.rfft2(x.float(), dim=(-2, -1))    # (B, C, H, W//2+1), complex
            mh = min(self.modes_h, H // 2)
            mw = min(self.modes_w, x_ft.shape[-1])

            out_ft = torch.zeros(B, self.w_pos.shape[1], H, x_ft.shape[-1], dtype=torch.cfloat, device=x.device)
            out_ft[:, :, :mh, :mw] = torch.einsum("bihw,iohw->bohw", x_ft[:, :, :mh, :mw], self.w_pos[:, :, :mh, :mw])
            out_ft[:, :, -mh:, :mw] = torch.einsum("bihw,iohw->bohw", x_ft[:, :, -mh:, :mw], self.w_neg[:, :, :mh, :mw])
            out = torch.fft.irfft2(out_ft, s=(H, W))
        return out.to(orig_dtype)


class FourierLayer2d(nn.Module):
    """One Neural-SPDE / FNO-style layer: global spectral conv + local pointwise
    conv, FiLM-conditioned on (t, E_inc), residual + GELU. FiLM's output projection
    is zero-initialized so every layer starts as (approximately) the identity."""

    def __init__(self, channels: int, modes_h: int, modes_w: int, cond_dim: int):
        super().__init__()
        self.spectral   = SpectralConv2d(channels, channels, modes_h, modes_w)
        self.pointwise  = nn.Conv2d(channels, channels, kernel_size=1)
        self.norm       = nn.GroupNorm(1, channels)   # channel-wise LayerNorm equivalent for 2D fields
        self.film       = nn.Sequential(nn.SiLU(), nn.Linear(cond_dim, channels * 2))
        nn.init.zeros_(self.film[-1].weight)
        nn.init.zeros_(self.film[-1].bias)

    def forward(self, x: torch.Tensor, cond: torch.Tensor):
        h = self.spectral(x) + self.pointwise(x)
        scale, shift = self.film(cond).chunk(2, dim=-1)
        h = self.norm(h) * (1 + scale[:, :, None, None]) + shift[:, :, None, None]
        return x + F.gelu(h)


class SpatialOperator(nn.Module):
    """Lifts a scalar (PHI, R) field to hidden_dim channels, applies a stack of
    FourierLayer2d spectral-operator layers, projects to out_channels. Shared
    architecture for both the drift network and the diffusion/jump-intensity
    network below -- only what the output is used *for* differs (see NoiseProcess).
    Output projection is zero-initialized (stable start: drift(t,y)~=0, and a
    moderate constant diffusion/rate via softplus(0)=log(2))."""

    def __init__(self, out_channels: int, hidden_dim: int, n_fourier_layers: int,
                 modes_h: int, modes_w: int, cond_dim: int):
        super().__init__()
        self.lift = nn.Conv2d(1, hidden_dim, kernel_size=1)
        self.layers = nn.ModuleList([
            FourierLayer2d(hidden_dim, modes_h, modes_w, cond_dim) for _ in range(n_fourier_layers)
        ])
        self.project = nn.Conv2d(hidden_dim, out_channels, kernel_size=1)
        nn.init.zeros_(self.project.weight)
        nn.init.zeros_(self.project.bias)

    def forward(self, y: torch.Tensor, cond: torch.Tensor):
        h = self.lift(y)
        for layer in self.layers:
            h = layer(h, cond)
        return self.project(h)


class InitialFieldNet(nn.Module):
    """Predicts the (mean, std) of the layer-0 energy-fraction field from
    incident-energy conditioning, trained via a Gaussian NLL against real layer-0
    data (folded into NeuralSPDE.teacher_forced_loss) -- consistent with how the
    drift/diffusion nets are trained, rather than a latent-noise generator with no
    direct training signal (an earlier version sampled from an untrained latent
    z -- teacher_forced_loss only ever scores *transitions* between real layers, so
    that generator's parameters never appeared in the loss and would have stayed at
    their random init forever). Output projection is zero-initialized for a stable
    start, same rationale as SpatialOperator."""

    def __init__(self, grid_shape: tuple, cond_dim: int, hidden_dim: int):
        super().__init__()
        self.H, self.W = grid_shape
        self.net = nn.Sequential(
            nn.Linear(cond_dim, hidden_dim), nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim), nn.SiLU(),
            nn.Linear(hidden_dim, self.H * self.W * 2),
        )
        nn.init.zeros_(self.net[-1].weight)
        nn.init.zeros_(self.net[-1].bias)
        # Zero bias gives mean0 = softplus(0) = ln(2) =~ 0.693 at init -- badly mismatched
        # against real layer-0 energy fractions (typically ~1e-4 scale), which used to
        # inflate the loss/gradient regardless of anything the noise process did (confirmed:
        # dominant grad_norm contributor before this fix). Bias the mean channel (first H*W
        # of the flat output, matching the .view(n,2,H,W) layout below) so mean0 starts near
        # 1e-3 instead -- still small relative to y's dynamic range but far closer to the
        # real scale than 0.693, and avoids picking an even-more-negative bias that could
        # itself cause its own scale/precision issues.
        with torch.no_grad():
            self.net[-1].bias[: self.H * self.W] = math.log(math.expm1(1e-3))

    def forward(self, e_emb: torch.Tensor):
        n = e_emb.shape[0]
        out = self.net(e_emb).view(n, 2, self.H, self.W)
        mean = F.softplus(out[:, 0:1])   # energy fraction must be >= 0
        std  = F.softplus(out[:, 1:2])
        return mean, std

    def sample(self, e_emb: torch.Tensor):
        mean, std = self.forward(e_emb)
        return (mean + std * torch.randn_like(std)).clamp_min(0.0)


# ── Driving noise processes (pluggable) ─────────────────────────────────────────

class NoiseProcess(nn.Module):
    """Pluggable driving process for the SPDE's stochastic forcing term.

    Subclasses implement:
      - transition(y_t, drift_dt, diffusion_out, dt) -> (mean, std): the Gaussian
        transition density used for the *training* NLL (see
        NeuralSPDE.teacher_forced_loss). Exact for Wiener-driven processes (that IS
        the Euler-Maruyama transition density); a moment-matched approximation for
        the jump process (see CompoundPoissonNoise).
      - increment(diffusion_out, dt) -> stochastic sample actually added to y during
        free-running *generation* (NeuralSPDE.simulate). For the jump process this
        is a real sparse, non-negative compound-Poisson draw, not a Gaussian one --
        training and sampling intentionally diverge there.

    `out_channels` tells SpatialOperator how many channels the diffusion network
    must output for this process (e.g. Poisson's jump rate needs only 1; a process
    needing extra learned per-voxel parameters would set this higher).

    Optionally override `auxiliary_loss(...)` -> per-element loss tensor (or None)
    for a noise process whose own mean contribution needs a training signal
    independent of drift_net -- see CompoundPoissonNoise for why this matters.
    Default: no auxiliary term.
    """
    out_channels = 1

    def auxiliary_loss(self, y_t, y_next, drift_dt, diffusion_out, dt, scale):
        return None

    def transition(self, y_t: torch.Tensor, drift_dt: torch.Tensor,
                   diffusion_out: torch.Tensor, dt: float):
        raise NotImplementedError

    def increment(self, diffusion_out: torch.Tensor, dt: float):
        raise NotImplementedError


class BrownianNoise(NoiseProcess):
    """Standard per-voxel-independent Wiener process (Ito), matching
    sde_demo.ipynb's CaloSDE.g() -- but with a learned spectral network in place of
    the fixed sigma*sqrt(|y|) form. diffusion_net's output is softplus'd into a
    per-voxel std; since this exactly is the Euler-Maruyama transition density of a
    Wiener-driven SDE, the training NLL below is exact, not an approximation."""
    out_channels = 1

    def transition(self, y_t, drift_dt, diffusion_out, dt):
        std = F.softplus(diffusion_out) * math.sqrt(dt)
        return y_t + drift_dt, std

    def increment(self, diffusion_out, dt):
        std = F.softplus(diffusion_out) * math.sqrt(dt)
        return std * torch.randn_like(std)


class ColoredBrownianNoise(BrownianNoise):
    """Spatially-correlated Wiener process (a discretized Q-Wiener process, the
    standard driving noise in the SPDE literature): draws are independent per
    Fourier mode with a fixed power-law spectral falloff (`decay`), then
    inverse-FFT'd to real space -- instead of BrownianNoise's per-voxel-independent
    draws. This is the more literally spatially-coupled ("P" in SPDE) choice of
    noise, vs. BrownianNoise's plain per-voxel Ito noise.

    Training NLL is inherited from BrownianNoise unchanged: it scores each voxel's
    *marginal* std correctly, but does not fit the induced cross-voxel covariance
    explicitly (that's fixed via `decay`, not something the NLL enforces) -- an
    exact joint likelihood would require scoring in the Fourier basis, where this
    noise is actually diagonal; skipped here for simplicity. Sampling (`increment`)
    uses the full spatially-correlated field.

    `decay` is a plain float, not an nn.Parameter: the training loss above never
    calls `increment`/`_spectral_filter` (only `transition`, inherited unchanged
    from BrownianNoise), so there is no gradient path that could ever move it --
    making it learnable would be misleading. Tune `decay_init` directly (larger =
    smoother/more correlated noise) if you want a different correlation length.
    """

    def __init__(self, grid_shape: tuple, decay_init: float = 1.5):
        super().__init__()
        self.grid_shape = grid_shape
        self.decay = decay_init

    def _spectral_filter(self, device):
        H, W = self.grid_shape
        kh = torch.fft.fftfreq(H, device=device).reshape(H, 1)
        kw = torch.fft.rfftfreq(W, device=device).reshape(1, W // 2 + 1)
        k2 = kh ** 2 + kw ** 2
        filt = (1.0 + k2).pow(-self.decay / 2)
        return filt / filt.pow(2).mean().sqrt()   # unit average power -> comparable scale to white noise

    def _colored_field(self, shape, device):
        B, C, H, W = shape
        real = torch.randn(B, C, H, W // 2 + 1, device=device)
        imag = torch.randn(B, C, H, W // 2 + 1, device=device)
        spec = torch.complex(real, imag) * self._spectral_filter(device)
        return torch.fft.irfft2(spec, s=(H, W))

    def increment(self, diffusion_out, dt):
        std = F.softplus(diffusion_out) * math.sqrt(dt)
        return std * self._colored_field(std.shape, std.device)


class CompoundPoissonNoise(NoiseProcess):
    """Jump-driven forcing: a compound Poisson process, closer to the true physics
    of discrete particle depositions (shot noise) than a continuous Wiener process
    -- and, unlike a Gaussian, naturally non-negative and sparse, matching real
    showers' heavily zero-inflated voxel occupancy (see cfm-dit_voxel/README.md,
    "Known issues": ~76% of voxels are exactly zero).

    diffusion_net's (softplus'd) output is the per-voxel jump *rate* lambda(t, y).
    `quantum` -- a single learned *global* scalar, not a spatial field -- is the
    typical energy-fraction size of one deposition; keeping it global (rather than
    per-voxel) keeps the jump count implied by a continuous residual well-defined
    without a non-differentiable round().

    `increment` draws a real compound-Poisson sample: N ~ Poisson(lambda*dt) jumps
    of size `quantum` each -- used at *generation* time, genuinely sparse/jump-like.

    `transition` instead returns the compound process's first two moments
    (mean = lambda*dt*quantum, var = lambda*dt*quantum^2) as a Gaussian
    moment-match, used only for the *training* NLL: an exact discrete count isn't
    recoverable from a continuous real-shower residual, so training fits the
    process's mean/variance (exact in the many-small-jumps / high-rate limit, by
    the compound-Poisson CLT) while sampling still draws real discrete jumps.

    Numerical stability note: var_jump shrinks quadratically with `quantum`, and
    `quantum` is a single free-floating scalar (not diluted across a spatial
    field like the drift/diffusion nets' weights are) -- so a bad step can shrink
    it, spike the NLL's 1/var term, and produce a much larger gradient than the
    Brownian processes typically see.

    An earlier version of this class hard-floored `rate`/`quantum` (rate_floor=0.05,
    quantum_floor=0.01) to stop this. That prevented the crash, but at a real cost:
    those floors are absolute lower bounds regardless of E_inc, so
    quantum_floor=0.01 forces a minimum single-jump size of *1% of E_inc* -- huge in
    absolute MeV for large showers, and applied at rate_floor's ~5% probability
    across all ~6300 voxel-transitions per shower, this injected large,
    energy-scale-proportional spurious energy into every generated shower (visible
    as discrete artifact peaks in the per-voxel hit-energy spectrum at exact
    multiples of quantum_floor*E_inc, and a permanently-elevated, non-decaying
    depth profile that never reaches proper shower containment). It also didn't
    fully fix the training pathology, just slowed it: `n_skipped_large` kept
    climbing across a real 100-epoch run instead of staying flat, as more voxels'
    rate settled at the floor's edge. See README.md "Known issues" for the full
    story and the generated-shower plots that caught this.

    Fixed properly in `NeuralSPDE.teacher_forced_loss` instead of here: `rate`/
    `quantum` are unfloored again (this class is back to plain softplus), and the
    loss detaches `std` before using it to weight/bound the residual (Huber-style,
    like LANTERN's variance-stabilized loss) -- so gradient descent can no longer
    reduce the loss merely by shrinking the reported uncertainty, only by fitting
    the mean better. That removes the collapse *incentive* at its root, rather
    than papering over its worst-case output with a floor.
    """
    out_channels = 1

    def __init__(self, init_quantum: float = 1e-2):
        super().__init__()
        self.log_quantum = nn.Parameter(torch.tensor(math.log(init_quantum)))

    def _quantum(self):
        return F.softplus(self.log_quantum)

    def _rate(self, diffusion_out):
        return F.softplus(diffusion_out)

    def transition(self, y_t, drift_dt, diffusion_out, dt):
        rate = self._rate(diffusion_out)
        q    = self._quantum()
        mean_jump = rate * dt * q
        var_jump  = rate * dt * q ** 2
        return y_t + drift_dt + mean_jump, torch.sqrt(var_jump)

    def increment(self, diffusion_out, dt):
        rate   = self._rate(diffusion_out)
        q      = self._quantum()
        counts = torch.poisson(rate * dt)
        return counts * q

    def auxiliary_loss(self, y_t, y_next, drift_dt, diffusion_out, dt, scale):
        # mu = y_t + drift_dt + mean_jump is under-determined: drift_net is unconstrained
        # (any sign, full spectral network) so it can fit mu entirely on its own, leaving
        # rate/quantum's gradient at ~0 once it does -- confirmed empirically, rate stayed
        # at ~0.66 (basically softplus(0), i.e. random init) after a full 30-epoch run, and
        # quantum barely moved from its init. At generation time this is catastrophic:
        # simulate() draws real Poisson jumps at that untrained, ~uniform rate on every one
        # of the ~6300 voxel-transitions per shower regardless of whether a jump belongs
        # there, while drift_net only cancels that noise's *mean*, not each actual sample --
        # generated showers came out ~200-1000x too much total energy. Fix: give mean_jump
        # its own regression target, independent of drift_dt, so it can't just sit at init.
        # relu(): only the *positive* part of a real transition is something a non-negative
        # jump process should explain; drift_net (signed) still handles negative-going and
        # residual/fine-tuning parts via the main loss.
        rate = self._rate(diffusion_out)
        q = self._quantum()
        mean_jump = rate * dt * q
        target = F.relu(y_next - y_t).detach()
        z = (mean_jump - target) / scale
        return F.huber_loss(z, torch.zeros_like(z), delta=1.0, reduction="none")


# ── Full model ───────────────────────────────────────────────────────────────

class NeuralSPDE(nn.Module):
    """Depth-stepped Neural SPDE for calorimeter showers -- see module docstring.

    Args
        grid_shape : (H, W) = (PHI, R) spatial grid, e.g. (16, 9)
        noise      : a NoiseProcess instance (BrownianNoise / ColoredBrownianNoise /
                     CompoundPoissonNoise) -- the driving stochastic process
        hidden_dim, n_fourier_layers, modes_h, modes_w : SpatialOperator width/depth
                     and spectral truncation, shared by the drift and diffusion nets
        cond_dim, time_dim : conditioning embedding widths
    """

    def __init__(self, grid_shape, noise: NoiseProcess, hidden_dim: int = 64,
                 n_fourier_layers: int = 4, modes_h: int = 8, modes_w: int = 5,
                 cond_dim: int = 128, time_dim: int = 32):
        super().__init__()
        self.grid_shape = grid_shape
        self.noise = noise

        self.time_embed   = DepthTimeEmbedding(time_dim)     # -> time_dim*4
        self.energy_embed = EnergyEmbedding(cond_dim)
        self.cum_embed    = CumulativeEnergyEmbedding(cond_dim)
        self.cond_merge   = nn.Sequential(
            nn.Linear(time_dim * 4 + cond_dim * 2, cond_dim), nn.SiLU(), nn.Linear(cond_dim, cond_dim)
        )

        self.drift_net     = SpatialOperator(1, hidden_dim, n_fourier_layers, modes_h, modes_w, cond_dim)
        self.diffusion_net = SpatialOperator(noise.out_channels, hidden_dim, n_fourier_layers, modes_h, modes_w, cond_dim)
        self.init_field     = InitialFieldNet(grid_shape, cond_dim, hidden_dim)

    def _cond_vec(self, t_idx: torch.Tensor, cond: torch.Tensor, cum_frac: torch.Tensor):
        t_emb = self.time_embed(t_idx)
        e_emb = self.energy_embed(cond)
        c_emb = self.cum_embed(cum_frac)
        return self.cond_merge(torch.cat([t_emb, e_emb, c_emb], dim=-1))

    def teacher_forced_loss(self, y_real: torch.Tensor, cond: torch.Tensor,
                             dt: float = 1.0, eps: float = 1e-6, huber_delta: float = 1.0,
                             drift_reg_weight: float = 1.0, global_reg_weight: float = 1.0,
                             drift_pos_mult: float = 1.0, scheduled_sampling_prob: float = 0.0):
        """y_real: (B, T, 1, H, W) real normalized showers (all T depth layers);
        cond: (B,) log10(E_inc/MeV). Scores every one of the T-1 real transitions
        in a single batched forward pass (B*(T-1) effective batch size) -- teacher
        forcing means every step's input is real data, so no sequential rollout is
        needed at training time. Also scores the layer-0 (initial-condition) field
        via InitialFieldNet's own NLL, since it's never touched by the transition
        loss above (nothing "transitions into" t=0).

        Not a plain Gaussian NLL: the residual is normalized by a *ground-truth*
        scale (`sqrt(|y_t|+eps)`, LANTERN's actual variance-stabilized-loss trick --
        shot-noise scaling from real data, not `std.detach()`) and then
        Huber-bounded, so a single extreme voxel can't produce an unbounded
        gradient. Using the model's own `std` (even detached) turned out not to be
        enough: detaching only stops it being an *optimization target*, but it's
        still the model's *prediction*, so as rate/quantum genuinely learn (see
        auxiliary_loss below), std legitimately shrinks in some regions, and
        1/std-derived blowups can recur as a side effect of normal learning, not
        just from a reward-for-collapsing incentive. A scale derived from fixed
        real data can't shrink no matter what the model does. This replaces an
        earlier plain-NLL version that let `std` collapse toward 0 to cheaply fit
        the zero-inflated majority, spiking the minority's 1/std^3 gradient term --
        confirmed on real runs for both BrownianNoise (freely-predicted std) and
        CompoundPoissonNoise (rate/quantum both drift toward 0 the same way); see
        README.md "Known issues".

        Caveat: since std is never used in the primary Huber term at all now, any
        parameter that *only* contributes to std and not to mu gets no signal from
        THAT term -- BrownianNoise's diffusion_net (std-only, no mean path) stays
        at its random init; Brownian training was already broken/deferred before
        this change (see README.md) so this doesn't regress anything currently in
        use. InitialFieldNet's std0 had the same problem but a dedicated fix below
        (nll0_std): it's genuinely used at generation time (sample_initial() draws
        mean0 + std0*randn()), and leaving it at its zero-init std0=softplus(0)=
        0.693 was confirmed to be the actual cause of the ~1700x generation-time
        energy overshoot, not drift_net or the jump process as first suspected --
        traced the free-running rollout step by step and found layer 0 alone
        already summed to ~40x E_inc at generation, barely changing over the
        following 44 steps. Fixed by giving std0 its own real target (the observed
        |y_real[:,0]-mean0| deviation), same auxiliary-loss pattern as
        CompoundPoissonNoise's rate/quantum.

        CompoundPoissonNoise has a second, subtler version of the same problem even
        though rate/quantum *do* feed mu (via mean_jump): mu = y_t + drift_dt +
        mean_jump is under-determined, and drift_net (unconstrained, full spectral
        network) is a much easier path for gradient descent to fit mu through than
        rate*dt*quantum -- confirmed empirically, rate/quantum stayed at ~their
        random init for a full 30-epoch run while drift_net alone fit the data.
        `noise.auxiliary_loss(...)` (called below if the noise process defines one)
        gives such processes an independent training signal so they can't just sit
        at init; see CompoundPoissonNoise.auxiliary_loss for the fix itself.

        `drift_reg_weight` penalizes drift_dt's squared magnitude directly. Even
        with auxiliary_loss giving rate/quantum their own signal, drift_net's much
        greater flexibility let it still absorb the bulk of the mean-fitting on a
        real run (confirmed: rate*quantum accounted for <1% of E_inc's worth of
        energy per shower even though the one-step teacher-forced loss converged to
        ~0). That's an exposure-bias problem: drift_net is only ever evaluated one
        step at a time against real data, never against its own free-running
        rollout, so a systematic per-step bias it learns compounds across all 44
        real generation steps with nothing to catch it (generated showers came out
        ~1700-1800x too much total energy). Penalizing drift_dt directly forces the
        jump process to carry the mean-fitting instead, which doesn't have the same
        compounding failure mode (each jump is an independent, physically bounded
        sample, not an additive per-step drift that free-runs on its own output).

        `drift_pos_mult` can make the penalty *asymmetric* (positive drift costing
        more than negative) instead of plain L2 -- motivated by an exposure-bias
        argument (real y_t is already ~0 by the late depth layers, so teacher
        forcing never scores drift_net on "elevated y at a late layer", a state
        only the model's own free-running rollout ever visits) and confirmed to fix
        the specific symptom it targeted: a checkpoint trained with
        drift_pos_mult=10 no longer showed drift_dt flipping positive past
        shower-max the way a drift_pos_mult=1 (plain L2) checkpoint did.

        BUT: that same drift_pos_mult=10 run was *worse* overall, not better --
        per-hit-energy EMD at E_inc=1 TeV went 135 -> 670, and the longitudinal
        profile went from plateauing after shower-max to actively exploding
        (generated total climbing to ~4x the real peak by the last layer, with
        highly unstable sample-to-sample variance). Root cause, again confirmed by
        instrumenting the rollout: squeezing drift_net's positive output just
        shifted the same mean-fitting burden onto CompoundPoissonNoise's rate net,
        whose predicted rate (rate_mean) stopped decaying with depth at all and
        instead grew monotonically and saturated ~50-100x higher than the
        drift_pos_mult=1 run -- because rate is conditioned on the current field y
        (not just t), so an elevated y (the same OOD state as above) predicts an
        even higher rate, which adds more energy, which elevates y further: a
        genuine positive-feedback loop, structurally worse than the additive
        drift-sign-flip bug it replaced. See README.md "Known issues" for the full
        numbers. Default is therefore back to drift_pos_mult=1.0 (mathematically
        identical to the original plain-L2 penalty, since
        relu(x)^2+relu(-x)^2 == x^2) -- the underlying containment problem (neither
        network has any signal for "how much energy have I already deposited", so
        nothing lets either one learn a real stopping rule) is real but still open;
        fixing it needs a different approach (e.g. a per-depth-layer aggregate loss
        term, or conditioning on cumulative deposited energy), not a one-sided
        penalty on a single network's output sign.

        UPDATE: cumulative-energy conditioning was added (see CumulativeEnergyEmbedding,
        `_cond_vec`'s `cum_frac` argument) -- drift_net/diffusion_net now see the fraction
        of E_inc deposited through the current layer, fixing the shape symptom above
        (generated z-profiles now decay past shower-max instead of plateauing/growing,
        confirmed on a real 100-epoch run). But it traded that bug for a new one: overall
        containment collapsed to ~2-9% of true across E_inc=1-1000 GeV (right shape,
        ~10x too low in magnitude). Root cause is the same exposure-bias pattern as
        drift_pos_mult above, one level up: `cum_frac` is exact ground truth during
        teacher forcing (derived straight from y_real), but at free-running generation
        it's built from the model's *own* rollout -- so the instant early layers deposit
        even slightly too little, `cum_frac` lags behind where a real shower would be at
        that depth, an input drift_net/diffusion_net never saw during training. Nothing
        taught them how to behave there, and the observed failure mode (collapse toward
        under-deposition) suggests they read "cum_frac looks low for this t" as "further
        along than I look" and suppress further, which lowers cum_frac even more next
        step: the same kind of compounding rollout feedback loop as the drift_pos_mult=10
        regression above, just running in the opposite direction.

        `scheduled_sampling_prob` (standard scheduled-sampling, Bengio et al. 2015,
        applied only to the `cum_frac` conditioning signal -- y_t itself stays real/
        teacher-forced, since local step correctness still benefits from a real state)
        is the fix: for a random subset of the batch, `cum_frac` is replaced by the
        cumulative sum from an actual no_grad self-rollout (`self.simulate`) with the
        model's *current* weights, instead of from y_real. That exposes drift_net/
        diffusion_net to the kind of off-manifold `cum_frac` they'll actually see during
        generation, and lets them learn a recovery behavior for it -- rather than only
        ever seeing `cum_frac` values that lie exactly on the real per-shower trajectory.
        Expected to be called with a value ramped up over training (see
        `_scheduled_sampling_prob`), not a training-long constant: early on, before the
        model fits individual transitions at all well, its self-rollout is close to
        noise, and conditioning on that noise would just corrupt cum_frac's training
        signal for no benefit -- the self-rollout only becomes a useful training signal
        once the per-step transitions it's built from are already roughly right.
        """
        B, T = y_real.shape[0], y_real.shape[1]
        y_t, y_next = y_real[:, :-1], y_real[:, 1:]
        t_idx = torch.arange(T - 1, device=y_real.device).unsqueeze(0).expand(B, -1)

        y_t_flat    = y_t.reshape(-1, *y_t.shape[2:])
        y_next_flat = y_next.reshape(-1, *y_next.shape[2:])
        t_idx_flat  = t_idx.reshape(-1)
        cond_flat   = cond.unsqueeze(1).expand(-1, T - 1).reshape(-1)

        # Fraction of E_inc deposited through layer t inclusive -- the containment
        # signal drift_net/diffusion_net were missing (see CumulativeEnergyEmbedding).
        # Derived straight from real data (teacher forcing), so it's exact, not a
        # rollout estimate; aligned with y_t's indexing via the [:, :-1] slice.
        cum_frac = torch.cumsum(y_real.sum(dim=(2, 3, 4)), dim=1)[:, :-1]

        if scheduled_sampling_prob > 0:
            # Self-rollout cum_frac, computed with the model's own current weights
            # (no_grad -- a fixed conditioning value to learn from, not something to
            # backprop through, same role as y_real itself). See docstring's "UPDATE"
            # paragraph for why this fixes the post-cum_frac under-containment collapse.
            with torch.no_grad():
                y_sim = self.simulate(cond, n_steps=T - 1, dt=dt)
                cum_frac_sim = torch.cumsum(y_sim.sum(dim=(2, 3, 4)), dim=1)[:, :-1]
            use_sim = (torch.rand(B, device=y_real.device) < scheduled_sampling_prob).unsqueeze(1)
            cum_frac = torch.where(use_sim, cum_frac_sim, cum_frac)

        cum_frac_flat = cum_frac.reshape(-1)

        c        = self._cond_vec(t_idx_flat, cond_flat, cum_frac_flat)
        drift_dt = self.drift_net(y_t_flat, c) * dt
        diff_out = self.diffusion_net(y_t_flat, c)

        mu, std = self.noise.transition(y_t_flat, drift_dt, diff_out, dt)
        # Ground-truth-derived scale (LANTERN's actual trick, sqrt(|x|+eps) shot-noise
        # scaling), NOT the model's own std.detach(): detaching std alone isn't enough --
        # it's still the model's *prediction*, so as rate/quantum genuinely learn (which
        # they now do, via auxiliary_loss below), std legitimately shrinks in places, and
        # 1/scale blows up again on any mismatch there (confirmed: reintroduced the exact
        # stall-guard collapse this whole redesign was meant to fix). A scale derived from
        # fixed real data can't shrink as a side effect of training, so this is genuinely
        # constant, not just non-differentiable.
        #
        # Scaled by max(y_t, y_next) -- neither endpoint alone is robust: scaling by
        # y_t alone over-penalizes voxels going from ~0 to a large real deposit (that
        # IS what a jump is); scaling by y_next alone flips the problem (equally
        # common: a voxel decaying from a large y_t toward ~0 gets a tiny scale
        # against a large mismatch, since mu starts near y_t at init when drift=0).
        # Both were confirmed empirically -- y_t-scale gave a ~620-loss floor
        # regardless of init_quantum; y_next-scale moved the dominant grad_norm
        # contribution from init_field to drift_net instead, same magnitude. The
        # larger of the two endpoints is a physically sensible shot-noise scale
        # either way (fluctuations track wherever the real activity is).
        scale = torch.sqrt(torch.maximum(y_t_flat, y_next_flat).abs() + eps)
        z = (y_next_flat - mu) / scale
        nll = F.huber_loss(z, torch.zeros_like(z), delta=huber_delta, reduction="none")

        aux = self.noise.auxiliary_loss(y_t_flat, y_next_flat, drift_dt, diff_out, dt, scale)
        aux_term = aux.mean() if aux is not None else 0.0

        # auxiliary_loss above is per-voxel-transition and still gets diluted: ~75% of
        # voxel-transitions correctly target 0, and averaging over all of them lets that
        # correct-majority swamp the pull from the rarer nonzero-target voxels that
        # actually carry the shower's energy -- confirmed by tracing a real rollout:
        # generated total landed ~180x below the real shower's total (0.004 vs 0.756)
        # even with per-voxel rate/quantum looking individually reasonable. Fix: a
        # *per-shower* aggregate term, immune to that dilution since each shower
        # contributes exactly one data point regardless of how many of its voxels are
        # (correctly) near-zero. mean_jump recovered generically as mu-y_t-drift_dt so
        # this works for any noise process with an additive mean contribution, not just
        # CompoundPoissonNoise (a no-op ~0 term for BrownianNoise, which has none).
        mean_jump_flat = (mu - y_t_flat - drift_dt).clamp_min(0.0)
        mean_jump_per_shower = mean_jump_flat.reshape(B, T - 1, *mean_jump_flat.shape[1:]).sum(dim=(1, 2, 3, 4))
        real_gain_per_shower = F.relu(y_next_flat - y_t_flat).reshape(
            B, T - 1, *y_t_flat.shape[1:]).sum(dim=(1, 2, 3, 4)).detach()
        scale_global = torch.sqrt(real_gain_per_shower.abs() + eps)
        z_global = (mean_jump_per_shower - real_gain_per_shower) / scale_global
        aux_global = F.huber_loss(z_global, torch.zeros_like(z_global), delta=huber_delta, reduction="none").mean()

        # Keep drift_dt small relative to the same ground-truth scale as everything else,
        # so it can only act as a minor correction -- not absorb the bulk of mean-fitting
        # the way it did unconstrained (see docstring). Squared, like a standard weight-decay
        # -style penalty: small deviations are cheap, large ones increasingly discouraged.
        #
        # Asymmetric: the positive part (energy-injecting drift) is penalized
        # drift_pos_mult harder than the negative part (containment drift) -- see
        # docstring for why a symmetric penalty doesn't reach the actual failure mode
        # (persistent small positive drift_dt past shower-max, invisible to teacher
        # forcing since real y_t is already ~0 there, but compounding across a
        # free-running rollout's remaining steps).
        drift_dt_scaled = drift_dt / scale
        drift_reg = drift_reg_weight * (
            drift_pos_mult * F.relu(drift_dt_scaled).pow(2).mean()
            + F.relu(-drift_dt_scaled).pow(2).mean()
        )

        e_emb0 = self.energy_embed(cond)
        mean0, std0 = self.init_field(e_emb0)
        # Same fix as above: ground-truth-derived (the real layer-0 field itself, no
        # model prediction involved), not std0.detach() -- no y_{-1} exists to use as
        # the "previous state" reference the way scale above uses y_t.
        scale0 = torch.sqrt(y_real[:, 0].abs() + eps)
        z0 = (y_real[:, 0] - mean0) / scale0
        nll0 = F.huber_loss(z0, torch.zeros_like(z0), delta=huber_delta, reduction="none")

        # std0 gets no gradient from nll0 above (mean0 is the only thing being fit there),
        # so -- exactly like CompoundPoissonNoise's rate/quantum before auxiliary_loss --
        # it just sits at its zero-init value (softplus(0)=0.693) forever. Confirmed to be
        # the actual, sole cause of the ~1700x generation-time energy overshoot (traced the
        # rollout step by step: layer-0 alone already summed to ~40x E_inc at generation,
        # barely changing over the following 44 steps -- not a rollout/exposure-bias problem
        # at all, just this). sample_initial() draws mean0 + std0*randn(), clamp_min(0): with
        # std0>>mean0, roughly half the H*W=144 per-voxel draws are negative (clamped to 0)
        # and the surviving positive half average ~std0 each -- 144 * ~0.4*0.693 =~ 40,
        # matching the traced value exactly. Give std0 its own target, same pattern as
        # CompoundPoissonNoise.auxiliary_loss: the real observed deviation of y_real[:,0]
        # from the (detached) mean prediction.
        std0_target = (y_real[:, 0] - mean0).detach().abs()
        z0_std = (std0 - std0_target) / scale0
        nll0_std = F.huber_loss(z0_std, torch.zeros_like(z0_std), delta=huber_delta, reduction="none")

        return (nll.mean() + nll0.mean() + nll0_std.mean() + aux_term + drift_reg
                + global_reg_weight * aux_global)

    def sample_initial(self, cond: torch.Tensor):
        e_emb = self.energy_embed(cond)
        return self.init_field.sample(e_emb)

    @torch.no_grad()
    def simulate(self, cond: torch.Tensor, n_steps: int, dt: float = 1.0):
        """Free-running generation: sample y_0, then integrate forward n_steps via
        Euler-Maruyama, using this model's chosen noise process at each step.
        Batch size is taken from cond.shape[0]. Returns (B, n_steps+1, 1, H, W):
        the full generated shower (all layers)."""
        device = cond.device
        n_samples = cond.shape[0]
        y   = self.sample_initial(cond)
        cum = y.flatten(1).sum(dim=1)   # fraction of E_inc deposited through layer 0 inclusive
        ys = [y]
        for t in range(n_steps):
            t_idx    = torch.full((n_samples,), t, device=device, dtype=torch.long)
            c        = self._cond_vec(t_idx, cond, cum)
            drift_dt = self.drift_net(y, c) * dt
            diff_out = self.diffusion_net(y, c)
            y = y + drift_dt + self.noise.increment(diff_out, dt)
            y = y.clamp_min(0.0)   # energy fraction can't be negative -- see module docstring
            cum = cum + y.flatten(1).sum(dim=1)
            ys.append(y)
        return torch.stack(ys, dim=1)


NOISE_PROCESSES = {
    "brownian":         BrownianNoise,
    "colored_brownian": ColoredBrownianNoise,
    "poisson":          CompoundPoissonNoise,
}


def build_noise_process(cfg: dict) -> NoiseProcess:
    """Constructs the NoiseProcess named by cfg["noise_type"] ("brownian" /
    "colored_brownian" / "poisson"), passing grid_shape to the one that needs it."""
    noise_type = cfg["noise_type"]
    if noise_type == "colored_brownian":
        H, W = cfg["voxel_shape"][1], cfg["voxel_shape"][2]
        return ColoredBrownianNoise((H, W))
    if noise_type == "poisson":
        # init_quantum sets std at random init (std ~= sqrt(rate*dt)*quantum, rate=softplus(0)
        # =~0.693 until the model trains) -- the 1e-2 class default is smaller than real
        # nonzero per-voxel-layer residuals; a reasonable starting point still helps early
        # generation quality, even though teacher_forced_loss's detached-scale Huber loss no
        # longer depends on this being exactly right for *training stability* (see
        # CompoundPoissonNoise's docstring and README.md "Known issues" for why the earlier
        # rate_floor/quantum_floor approach was dropped in favor of that).
        return CompoundPoissonNoise(init_quantum=cfg.get("init_quantum", 1e-2))
    return NOISE_PROCESSES[noise_type]()


def scheduled_sampling_prob(cfg: dict, epoch: int) -> float:
    """Epoch-dependent scheduled-sampling probability for teacher_forced_loss's
    `cum_frac` conditioning (see its docstring's "UPDATE" paragraph): 0 before
    cfg["scheduled_sampling_start_epoch"], then ramps linearly to
    cfg["scheduled_sampling_max_prob"] over cfg["scheduled_sampling_ramp_epochs"],
    held there after. Ramped rather than constant from epoch 0 -- see
    teacher_forced_loss's docstring for why turning it on before the model fits
    individual transitions reasonably well would just corrupt cum_frac's signal
    with noise instead of teaching a useful recovery behavior. All three cfg keys
    default such that scheduled sampling is off entirely unless opted into."""
    start = cfg.get("scheduled_sampling_start_epoch", None)
    if start is None:
        return 0.0
    ramp  = cfg.get("scheduled_sampling_ramp_epochs", 1)
    max_p = cfg.get("scheduled_sampling_max_prob", 0.5)
    if epoch < start:
        return 0.0
    return max_p * min(1.0, (epoch - start) / max(ramp, 1))


def build_model(cfg: dict) -> NeuralSPDE:
    T, H, W = cfg["voxel_shape"]
    return NeuralSPDE(
        grid_shape       = (H, W),
        noise            = build_noise_process(cfg),
        hidden_dim       = cfg["hidden_dim"],
        n_fourier_layers = cfg["n_fourier_layers"],
        modes_h          = cfg["modes_h"],
        modes_w          = cfg["modes_w"],
        cond_dim         = cfg["cond_dim"],
        time_dim         = cfg["time_dim"],
    )


def train(cfg: dict, train_loader, test_loader=None):
    """cfg["mode"] must be "train" (fresh start, ignoring any existing
    checkpoints) or "resume" (continue from the latest checkpoint in
    cfg["ckpt_dir"], required to exist). "eval" is not a valid mode here --
    see load_nspde_checkpoint for that path."""
    if cfg["mode"] not in ("train", "resume"):
        raise ValueError(f'train() requires cfg["mode"] in ("train", "resume"), got {cfg["mode"]!r}')

    device   = cfg["device"]
    ckpt_dir = Path(cfg["ckpt_dir"])
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(cfg.get("seed", 0))

    model = build_model(cfg).to(device)

    if cfg.get("compile", False):
        model = torch.compile(model)

    n_params     = sum(p.numel() for p in model.parameters())
    param_bytes  = sum(p.numel() * p.element_size() for p in model.parameters())
    buffer_bytes = sum(b.numel() * b.element_size() for b in model.buffers())
    print(f"  Noise process : {cfg['noise_type']}")
    print(f"  Parameters    : {n_params / 1e6:.2f} M")
    print(f"  VRAM          : {(param_bytes + buffer_bytes) / 1024**3:.3f} GiB")

    opt = AdamW(model.parameters(), lr=cfg["lr"], weight_decay=1e-4)

    warmup_epochs = cfg.get("warmup_epochs", 0)
    if warmup_epochs > 0:
        warmup = LinearLR(opt, start_factor=1e-2, end_factor=1.0, total_iters=warmup_epochs)
        cosine = CosineAnnealingLR(opt, T_max=cfg["epochs"] - warmup_epochs, eta_min=1e-6)
        sched  = SequentialLR(opt, schedulers=[warmup, cosine], milestones=[warmup_epochs])
    else:
        sched = CosineAnnealingLR(opt, T_max=cfg["epochs"], eta_min=1e-6)

    # bf16 (not float16): same exponent range as fp32, so it doesn't overflow the way
    # float16 does on large activations -- see cfm_dit_voxel.py's train() for the
    # training instability this convention was adopted to avoid in this repo. Unlike
    # float16, bf16 needs no loss-scaling GradScaler -- which also wouldn't work here
    # anyway: SpectralConv2d's w_pos/w_neg are complex64 parameters, and GradScaler's
    # unscale_() has no CUDA kernel for complex-dtype grads.
    amp_dtype = torch.bfloat16

    start_epoch = 0
    loss_history = []
    test_loss_history = []
    stall_streak = 0

    if cfg["mode"] == "resume":
        latest = sorted(ckpt_dir.glob("ckpt*.pt"))
        if not latest:
            raise FileNotFoundError(f'mode="resume" but no checkpoints found in {ckpt_dir}')
        state = torch.load(latest[-1], map_location=device)
        model.load_state_dict(state["model"])
        opt.load_state_dict(state["opt"])
        sched.load_state_dict(state["sched"])
        start_epoch = state["epoch"] + 1
        print(f"Resumed from {latest[-1]}  (epoch {start_epoch})")

    grad_skip_mult = cfg.get("grad_skip_mult", float("inf"))

    for epoch in range(start_epoch, cfg["epochs"]):
        model.train()
        epoch_loss = 0.0
        n_skipped, n_skipped_large = 0, 0
        grad_norm_sum, grad_norm_max = 0.0, 0.0
        ss_prob = scheduled_sampling_prob(cfg, epoch)

        for y, cond, _e_inc in train_loader:
            y, cond = y.to(device), cond.to(device)

            with torch.autocast("cuda", dtype=amp_dtype, enabled=(device == "cuda")):
                loss = model.teacher_forced_loss(y, cond, dt=cfg.get("dt", 1.0), drift_reg_weight=cfg.get("drift_reg_weight", 1.0), global_reg_weight=cfg.get("global_reg_weight", 1.0), drift_pos_mult=cfg.get("drift_pos_mult", 1.0), scheduled_sampling_prob=ss_prob)

            loss.backward()
            grad_norm = nn.utils.clip_grad_norm_(model.parameters(), cfg["grad_clip"])
            grad_norm_finite = torch.isfinite(grad_norm)
            # See cfm_dit_voxel.py's train() for why both isfinite() AND a magnitude
            # cutoff are needed -- a huge-but-finite pre-clip norm can still corrupt
            # weights via clip_grad_norm_'s own rescale.
            grad_norm_ok = grad_norm_finite and grad_norm <= cfg["grad_clip"] * grad_skip_mult
            if grad_norm_ok:
                opt.step()
                grad_norm_sum += grad_norm.item()
                grad_norm_max = max(grad_norm_max, grad_norm.item())
            elif grad_norm_finite:
                n_skipped_large += 1
                print(f"  [skip] grad norm {grad_norm.item():.3e} > {grad_skip_mult}x grad_clip"
                      f" at epoch {epoch+1} -- step skipped")
            else:
                n_skipped += 1
                print(f"  [skip] non-finite grad norm ({grad_norm.item()}) at epoch {epoch+1} -- step skipped")
            opt.zero_grad()

            epoch_loss += loss.item()

        sched.step()
        avg_loss = epoch_loss / len(train_loader)
        loss_history.append(avg_loss)

        n_finite = len(train_loader) - n_skipped - n_skipped_large
        grad_norm_mean = grad_norm_sum / n_finite if n_finite else float("nan")

        # Loud stall guard: a run where the grad-norm guard rejects most/all steps for
        # several consecutive epochs is not learning, even though loss/weights stay
        # finite and the run otherwise completes normally -- exactly what happened
        # silently for 99 epochs in the noise_type="brownian" run (see README.md).
        # Fail fast instead of burning GPU-hours on a frozen model.
        skip_frac = (n_skipped + n_skipped_large) / len(train_loader)
        stall_streak = stall_streak + 1 if skip_frac > cfg.get("max_skip_frac", 0.5) else 0
        print(f"  skip_frac={skip_frac:.2%}" + (f"  (stall streak: {stall_streak})" if stall_streak else ""))
        if stall_streak >= cfg.get("skip_patience", 3):
            raise RuntimeError(
                f"Training stalled: {stall_streak} consecutive epochs with skip_frac > "
                f"{cfg.get('max_skip_frac', 0.5):.0%} (grad-norm guard rejecting most/all steps). "
                f"Model is very likely not learning -- stopping instead of completing a broken run."
            )

        if wandb.run is not None:
            wandb.log({"grad_norm_mean": grad_norm_mean, "grad_norm_max": grad_norm_max,
                       "n_skipped": n_skipped, "n_skipped_large": n_skipped_large,
                       "scheduled_sampling_prob": ss_prob}, step=epoch + 1)

        if (epoch + 1) % cfg["log_every"] == 0:
            log_dict = {"train_loss": avg_loss, "learning_rate": sched.get_last_lr()[0]}
            msg = (f"Epoch {epoch+1:4d}/{cfg['epochs']}  |  loss={avg_loss:.5f}"
                   f"  grad_norm(mean/max)={grad_norm_mean:.3f}/{grad_norm_max:.3f}"
                   + (f"  ss_prob={ss_prob:.3f}" if ss_prob > 0 else ""))
            if n_skipped or n_skipped_large:
                msg += f"  (skipped {n_skipped} non-finite, {n_skipped_large} outlier-magnitude steps)"

            if test_loader is not None:
                model.eval()
                test_epoch_loss = 0.0
                with torch.no_grad():
                    for y, cond, _e_inc in test_loader:
                        y, cond = y.to(device), cond.to(device)
                        with torch.autocast("cuda", dtype=amp_dtype, enabled=(device == "cuda")):
                            loss = model.teacher_forced_loss(y, cond, dt=cfg.get("dt", 1.0), drift_reg_weight=cfg.get("drift_reg_weight", 1.0), global_reg_weight=cfg.get("global_reg_weight", 1.0), drift_pos_mult=cfg.get("drift_pos_mult", 1.0))
                        test_epoch_loss += loss.item()
                avg_test_loss = test_epoch_loss / len(test_loader)
                test_loss_history.append((epoch + 1, avg_test_loss))
                log_dict["test_loss"] = avg_test_loss
                msg += f"  test_loss={avg_test_loss:.5f}"

            msg += f"  lr={sched.get_last_lr()[0]:.2e}"
            print(msg)
            if wandb.run is not None:
                wandb.log(log_dict, step=epoch + 1)

        if (epoch + 1) % cfg["save_every"] == 0:
            finite_weights = all(torch.isfinite(p).all() for p in model.parameters())
            if not math.isfinite(avg_loss) or not finite_weights:
                print(f"  -> epoch {epoch+1}: non-finite loss or weights, skipping checkpoint save")
            else:
                ckpt_path = ckpt_dir / f"ckpt{datetime.datetime.now().strftime('%Y-%m-%d_%H-%M')}_epoch{epoch+1:04d}.pt"
                torch.save({
                    "epoch":  epoch,
                    "model":  model.state_dict(),
                    "opt":    opt.state_dict(),
                    "sched":  sched.state_dict(),
                    "cfg":    cfg,
                }, ckpt_path)
                print(f"  -> saved {ckpt_path}")

    return model, loss_history, test_loss_history


def load_nspde_checkpoint(cfg: dict):
    device   = cfg["device"]
    ckpt_dir = Path(cfg["ckpt_dir"])
    ckpts    = sorted(ckpt_dir.glob("ckpt*.pt"))
    if not ckpts:
        raise FileNotFoundError(f"No checkpoints found in {ckpt_dir}")

    state      = torch.load(ckpts[-1], map_location=device)
    loaded_cfg = state["cfg"]
    print(f"Loading {ckpts[-1]}  (epoch {state['epoch'] + 1})")
    print(loaded_cfg)

    model = build_model(loaded_cfg).to(device)

    # torch.compile-wrapped checkpoints (cfg["compile"]=True) prefix every key with
    # "_orig_mod." -- strip it so this loads regardless of how the checkpoint was saved.
    state_dict = {
        (k[len("_orig_mod."):] if k.startswith("_orig_mod.") else k): v
        for k, v in state["model"].items()
    }
    model.load_state_dict(state_dict)
    model.eval()

    n_params     = sum(p.numel() for p in model.parameters())
    param_bytes  = sum(p.numel() * p.element_size() for p in model.parameters())
    buffer_bytes = sum(b.numel() * b.element_size() for b in model.buffers())
    print(f"  Parameters : {n_params / 1e6:.2f} M  |  VRAM : {(param_bytes + buffer_bytes) / 1024**3:.3f} GiB")
    print(f"Model loaded from epoch {state['epoch'] + 1}.")
    return model, loaded_cfg


def generate_nspde(model: NeuralSPDE, cfg: dict, inverse, n_samples: int = 4, e_inc_gev: float = 10.0):
    """Generate shower samples conditioned on incident energy. `inverse(y_norm,
    e_inc_mev)` maps the model's normalized (energy-fraction) output back to MeV --
    see nspde2d-voxel.ipynb for its definition (simply y_norm * e_inc_mev, since the
    state is already linear, not log-normalized)."""
    model.eval()
    device    = cfg["device"]
    T         = cfg["voxel_shape"][0]
    e_inc_mev = e_inc_gev * 1e3
    cond      = torch.full((n_samples,), math.log10(e_inc_mev), device=device)
    e_inc     = torch.full((n_samples,), e_inc_mev, device=device)
    ys = model.simulate(cond, n_steps=T - 1, dt=cfg.get("dt", 1.0))
    return inverse(ys.cpu().numpy(), e_inc.cpu().numpy())
